### create user
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "email": "dsdfdfdffd@gmail.com",
    "password": "samplepassword",
    "type": "delivery"
}


###
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "email": "sampleEcomUser1@gmail.com",
    "password": "samplepassword",
    "type": "ecommerce"
}

### login user
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    "email": "sampleEcomUser1@gmail.com",
    "password": "samplepassword",
    "type": "ecommerce"
}

###
POST http://localhost:8080/accounts/delivery_services/config/charges HTTP/1.1
Content-Type: application/json
Api-Key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVzSW4iOiI5MGQiLCJkYXRhIjp7InVzZXIiOnsiZW1haWwiOiJzYW1wbGVkZWxhY2MxMEBnbWFpbC5jb20iLCJ0eXBlIjoiZGVsaXZlcnkifX0sImlhdCI6MTY2MzAwMjM4NH0.rMGJDpXp5xcn9ENIEQhkUSVndQsymV8j8q5oMyM2iXI

{
    "country": "Sri Lanka",
    "countryCode": "LK",
    "stateFees": [
        {
            "state": "gampaha",
            "stateCode": "456231",
            "fee": 250
        }
    ]
}

####

GET http://localhost:8080/protected HTTP/1.1
Access-Token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjMwODY0NzEsImV4cCI6MTY2MzI1OTI3MSwiYXVkIjoiZWNvbW1lcmNlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwic3ViIjoiNjMyMDYzM2M5Y2YzYmEyMDkxNWQ5YTU4In0.qP8koD-xzXdmFYD78yI_1aOB-Sk7TC7QI3xGiTFdhE8


### list plans
GET http://localhost:8080/plans HTTP/1.1
Access-Token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjMwODY0NzEsImV4cCI6MTY2MzI1OTI3MSwiYXVkIjoiZWNvbW1lcmNlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwic3ViIjoiNjMyMDYzM2M5Y2YzYmEyMDkxNWQ5YTU4In0.qP8koD-xzXdmFYD78yI_1aOB-Sk7TC7QI3xGiTFdhE8